import json

# Load metadata
with open("metadata.json", "r", encoding="utf-8") as f:
    meta = json.load(f)

video_title = meta["title"]
video_tags = meta["tags"].split(",")

body = {
    "snippet": {
        "title": video_title,
        "description": "Generated by AI",
        "tags": video_tags
    },
    "status": {
        "privacyStatus": "public"
    }
}

# Upload thumbnail
youtube.thumbnails().set(
    videoId=video_id,
    media_body="thumbnail.jpg"
).execute()

print("Uploaded successfully with title + tags + thumbnail!")
