import os, json
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials

CLIENT_ID = os.getenv("YT_CLIENT_ID")
CLIENT_SECRET = os.getenv("YT_CLIENT_SECRET")
REFRESH_TOKEN = os.getenv("YT_REFRESH_TOKEN")

creds = Credentials.from_authorized_user_info({
    "client_id": CLIENT_ID,
    "client_secret": CLIENT_SECRET,
    "refresh_token": REFRESH_TOKEN
})

youtube = build("youtube", "v3", credentials=creds)

with open("metadata.json", "r", encoding="utf-8") as f:
    meta = json.load(f)

request_body = {
    "snippet": {
        "title": meta["title"],
        "description": "Generated by AI 🤖",
        "tags": meta["tags"].split(",")
    },
    "status": {
        "privacyStatus": "public"
    }
}

media = MediaFileUpload("output.mp4")

response = (
    youtube.videos()
    .insert(part="snippet,status", body=request_body, media_body=media)
    .execute()
)

video_id = response["id"]

# Apply thumbnail
youtube.thumbnails().set(
    videoId=video_id, media_body=MediaFileUpload("thumbnail.png")
).execute()

print(f"✔ Uploaded successfully: https://youtube.com/watch?v={video_id}")
